<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5293" started-at="2018-05-02T12:54:39Z" finished-at="2018-05-02T12:54:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5293" started-at="2018-05-02T12:54:39Z" finished-at="2018-05-02T12:54:44Z">
      <class name="selenium_notes.HandleWindows">
        <test-method status="FAIL" signature="handleWindow()[pri:0, instance:selenium_notes.HandleWindows@5c3bd550]" name="handleWindow" duration-ms="18" started-at="2018-05-02T12:54:39Z" finished-at="2018-05-02T12:54:39Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at selenium_notes.HandleWindows.handleWindow(HandleWindows.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handleWindow -->
        <test-method status="PASS" signature="startUp()[pri:0, instance:selenium_notes.HandleWindows@5c3bd550]" name="startUp" duration-ms="4868" started-at="2018-05-02T12:54:39Z" finished-at="2018-05-02T12:54:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:selenium_notes.HandleWindows@5c3bd550]" name="tearDown" is-config="true" duration-ms="368" started-at="2018-05-02T12:54:43Z" finished-at="2018-05-02T12:54:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- selenium_notes.HandleWindows -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
